### ISSUE TITLE
如何避免作者文章難度分類錯誤。

### ISSUE THREAD

**Issue by tpemartin** [tpemartin/E.Major-Meeting#14]
作者分類不適，有兩種情況： 

（1）作者選Juice，但看過文章的人多數選Issue Chat。
（2）作者選Issue Chat，但多數人選Juice。

 (2) 我覺得不用改，不用打擊作者信心。 （1）則要盡量避免。

**Comment by PoMingChen** [comment]
這邊我想要再大約花5min的時間討論(確認)，每文一字要放在文章最前面或最後面

**Comment by PoMingChen** [comment]
每日一字，放最後面。
內文可以自己寫或摘要成中文
