### ISSUE TITLE
一個採訪規劃構想

### ISSUE THREAD

**Issue by tpemartin** [tpemartin/E.Major-Meeting#23]
最近經濟學人有一篇文章：

Nudge comes to shove
Policymakers around the world are embracing behavioural science

這篇文章是有關實驗經濟正在改變政策制定的文章。老師有個想法，我們有沒有可能將這文章加上對陳儀老師的採訪，而成為一個很有特色的介紹文，而且讀者會跟經濟系老師再拉近些距離。

**Comment by ChenChingChih** [comment]
@tpemartin 這個構想很棒耶!我是讀者也會想知道政策制定時會先用哪些方式去測試民眾的反映!
