### ISSUE TITLE
成員申請Github帳號並回報

### ISSUE THREAD

**Issue by tpemartin** [tpemartin/E.Major-Meeting#3]

**Comment by PoMingChen** [comment]
請到下面的網頁點Request a discount. https://education.github.com/
依序操作，帳號必須用台北大學gmail才可以申請 
帳 : s(學號)@gm.ntpu.edu.tw
密 : 身分證前八碼

**Comment by tpemartin** [comment]
成員申請完，請把你的使用者名稱貼在FB E.Major幹部 messenger裡，我們會陸續把你們加進來這個repo.
