### ISSUE TITLE
# hastag 分類問題

### ISSUE THREAD

**Issue by tpemartin** [tpemartin/E.Major-Meeting#5]

**Comment by tpemartin** [comment]
Morning Juice: 短文，沒有太專業
Coffee break （暫定）： 短文，很專業
 ：類似Briefing，大趨勢
：自家專業報導

**Comment by PoMingChen** [comment]
成員充實 : 
1/ 每周一篇morning juice ，一篇issue chat
2/ 行銷部若個別存量不足會提醒
3/ 要發表的文章放到都放到Github上面，放到E-Major FB的repo，然後po再issue，再自己標上label
